name: Java tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Setup Java
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '20'

    - name: Start frontend service
      run: |
        docker run -d --name frontend --network host -p 3000:3000 -v $PWD/application/web:/home/frontend node:20 bash -c "cd /home/frontend && npm install && npm run dev"
      env:
        API_URL: ${{ secrets.FRONTEND_API_URL }}

    - name: Start backend service
      run: |
        docker run -d --name backend --network host -p 3333:3333 -v $PWD/application/api:/home/backend node:20 bash -c "cd /home/backend && npm install && npm run dev"

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Build and Run Tests
      run: mvn clean install

    - name: Slack Notification
      if: always()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: zombieplus
        SLACK_COLOR: ${{ job.status }} 
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: Post Title
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
